name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4 #github.com/actions/checkout 
    - run: docker build . - waqcas/next-js-app
    - run: echo ${{ DOCKERHUB_PASSWORD }} | docker login -u ${{ DOCKERHUB_USERNAME }} --password-stdin
    - run: docker push waqcas/next-js-app
                     DOCKERHUB_PASSWORD