name: AWS Infra Provisioning
on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  terraform_linting_job:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.14.0

    - name: Terraform Init
      run: terraform init

    - name: Printing Variables
      run: echo "GIT HUB REFS ${{ github.ref }}""
      run: echo "GITHUB EVENT NAME ${{ github.event_name }}""

    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    #   run: terraform apply -auto-approve -input=false

  